# Generated by Django 3.0.4 on 2020-03-08 12:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('birth_date', models.DateField(null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pages', models.IntegerField()),
                ('published_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('authors', models.ManyToManyField(related_name='book_author', to='app.Author')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUser',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('date_end', models.DateTimeField()),
                ('date_finish', models.DateTimeField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book', 'date_start')},
            },
        ),
    ]
