# Generated by Django 3.0.4 on 2020-03-08 14:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200308_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookloan',
            name='id',
        ),
        migrations.AddField(
            model_name='bookloan',
            name='book_loan_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='date_finish',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='date_start',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.LibraryUser'),
        ),
    ]
