# Generated by Django 3.0.4 on 2020-03-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200308_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookloan',
            old_name='book_loan_id',
            new_name='id',
        ),
    ]
